version: '3.3'

services: 
  medi-db:
    container_name: medidb
    image: mysql:5.7
    restart: always
    env_file: 
      - .env
    volumes: 
      - medi-db-volume:/var/lib/mysql:rw
      - ./../medi-database/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - medi-network-api
      - medi-network-utility
    ports:
      - 3306:3306

  adminer:
    container_name: medidbutility
    depends_on: 
      - medi-db
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks: 
      - medi-network-utility
  api:
    container_name: meditestbackend
    build:
      context: ./../medi-backend
      dockerfile: Dockerfile
    depends_on: 
      - medi-db
    image: medi-backend
    restart: always
    ports:
      - 8000:8000
    networks: 
      - medi-network-api

volumes:
  medi-db-volume:

networks: 
  medi-network-api:
  medi-network-utility: